//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.23 at 11:59:35 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tekup.de/soap/models/whitetest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.tekup.MustaphaConsumer.WhiteTestsClasses;
